version: '3.8'

services:
  gin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin
    ports:
      - "8080:8080"
    expose:
      - 8080
  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - .:/byte-battle_backend/migrations
    command:
      [ "-path", "byte-battle_backend/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=${POSTGRES_SSLMODE}", "up" ]
  postgres:
    image: postgres:alpine
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped


